### PR TITLE
Feat: Added utility classes for Grid layouts

### PR DESCRIPTION
**Pull request by kjais1720**
Created utility classes for Grid layouts
- `.d-grid` to apply `display:grid` to a container
- `.grid-col-2` to create a 2 column layout
- `.grid-col-3` to create 3 column-layout
- `.grid-autofit-sm` to create columns of 10 rem to 100% of width
- `.grid-autofit-md` to create columns of 20 rem to 100% of width
- `.grid-autofit-lg` to create columns of 30 rem to 100% of width
- Preview link 👇
https://deploy-preview-21--tarang-ui.netlify.app/docs/grid/grids

### CODE REVIEW

**Review by shubhamkumar648 — APPROVED** [review]
Everything looks good!

**Review by nakulsharma15 — COMMENTED** [review]
Everything looks good. No changes required

**Comment by vaibhav-mahalle** [comment]
Is it possible to commit changes periodically? reviewing a a lot of changes iin one go is tough.

**Comment by vaibhav-mahalle** [comment]
The detailed comment about the contents of pr is good. Will start following that practice.

**Pull request merged**
